service: phpmyadmin2
runtime: php74

entrypoint: serve public.php

handlers:

- url: /(.+\.(ico|jpg|png|gif))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif))$

- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$

- url: .*
  script: auto
  secure: always
  login: admin
